### PR TITLE
change variable names for readability (in semant)

### PR DESCRIPTION
**Pull request by nnhoang**

### CODE REVIEW

**Comment by nnhoang** [comment]
can I only assign 1 person?

**Comment by jzacsh** [comment]
+1 looks good

**Comment by jzacsh** [comment]
@nnhoang you can `@`mention people  (like I did to you), but yeah, I think only one assignee

**Comment by nnhoang** [comment]
I probably won't merge this... just realized `CtxMap` is just a general "class" to create maps, so we should probably keep a general name

**Comment by jzacsh** [comment]
Ah, yeah, makes sense. Ocaml. Feel free to close this then

**Pull request closed without merging**
