### PR TITLE
update syntax for find without variable id after keyword FIND

### PR DESCRIPTION
**Pull request by rxie25**

### CODE REVIEW

**Comment by jzacsh** [comment]
I think it might looks bad if our language just let's ANYTHING pass through like this. A "hello world" compiler submission that accepts the below `eq` file _(which this pull request accepts)_ just highlights that we're a million miles away from the LRM and variable/equation analysis we had discussed with the professor:

```c
Ctx = {
  y = { x + 1; }
}

Ctx:find { //one of our compiler's purposes was to force users to provide missing "x" and prove that we detected it correctly
  print(y);
}
```

**Comment by rxie25** [comment]
the semantic analysis should be able to raise error on the example because x is not given. Not because we don't have a variable name after find. Essentially we won't be able to print a simple text out without solving some kind of equation first. I think It's really just a design choice. Either way works for me.

**Comment by jzacsh** [comment]
> the semantic analysis should be able to raise error on the example because x is not given.

Yes, that's what I'm trying to say. Making that ^ example snippet works just highlights that our compiler essentially doesn't do anything right now _(ie: until we solve that, we've just added a noop-`find` keyword into a C-like language, and for no reason)_

**Comment by jzacsh** [comment]
my point is, this is what the TA's advice was about _not just updating the scanner & parser_ for no reason. we should update as a side-effect, *while* we try to fix real issues in the codegen/semantic-analysis.

**Comment by rxie25** [comment]
Ok, I will close this request.

**Pull request closed without merging**
